name: Linux
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bundle WebUI Bridge
        run: |
          npm i -g esbuild
          bridge/build.sh
      - uses: actions/cache@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge

  build-release:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        compiler: [GCC, Clang]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge
          fail-on-cache-miss: true
      - name: Build
        run: |
          if [ "${{ matrix.compiler }}" == "Clang" ]; then
            sudo ln -s llvm-ar-13 /usr/bin/llvm-ar
            sudo ln -s llvm-ranlib-13 /usr/bin/llvm-ranlib
          fi
          make
      - name: Prepare Artifact
        run: |
          cp -r include dist
          artifact=${{ runner.os }}-${{ matrix.compiler }}-x64
          # Add the ARTIFACT name(`,,` ^= lowercase shell param) as GitHub environment variable.
          echo "ARTIFACT=${artifact,,}" >> $GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: dist
      - name: Release Artifact
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARTIFACT }}
