name: macOS
on:
  workflow_call:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bundle WebUI Bridge
        run: |
          npm i -g esbuild
          bridge/build.sh
      - uses: actions/cache@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge

  build-release:
    needs: setup
    runs-on: macos-latest
    name: macOS
    permissions:
      contents: write
    strategy:
      matrix:
        compiler: [Clang]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge
          fail-on-cache-miss: true
      - name: Build
        run: |
          make
      - name: Prepare Artifacts
        run: |
          cp -r include dist
          # Add the ARTIFACT name(lowercased) as GitHub environment variable.
          artifact=$(echo ${{ runner.os }}-${{ matrix.compiler }}-x64 | tr '[:upper:]' '[:lower:]')
          echo "ARTIFACT=$artifact" >> $GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: dist
      - name: Release Artifact
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.ARTIFACT }}
          files: dist
